"""empty message

Revision ID: 55d479bf4211
Revises: 9fcfbd125c5d
Create Date: 2018-06-05 10:51:31.452761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55d479bf4211'
down_revision = '9fcfbd125c5d'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_data():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detailitem_test', sa.Column('desc', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade_data():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detailitem_test', 'desc')
    # ### end Alembic commands ###

