"""empty message

Revision ID: 6f7fab31143b
Revises: 346741f3a4ea
Create Date: 2018-06-05 17:10:18.180481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f7fab31143b'
down_revision = '346741f3a4ea'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_data():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('qaitem_itemid_key', 'qaitem', type_='unique')
    op.drop_constraint('reviewitem_itemid_key', 'reviewitem', type_='unique')
    # ### end Alembic commands ###


def downgrade_data():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('reviewitem_itemid_key', 'reviewitem', ['itemid'])
    op.create_unique_constraint('qaitem_itemid_key', 'qaitem', ['itemid'])
    # ### end Alembic commands ###

