"""empty message

Revision ID: 7aeb32483014
Revises: 55d479bf4211
Create Date: 2018-06-05 11:03:39.500258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aeb32483014'
down_revision = '55d479bf4211'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_data():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DetailItem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itemid', sa.Text(), nullable=True),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.Column('sku', sa.Text(), nullable=True),
    sa.Column('rating_count', sa.Text(), nullable=True),
    sa.Column('warranty', sa.Text(), nullable=True),
    sa.Column('seller_name', sa.Text(), nullable=True),
    sa.Column('question_count', sa.Text(), nullable=True),
    sa.Column('positive_rating', sa.Text(), nullable=True),
    sa.Column('json_data', sa.Text(), nullable=True),
    sa.Column('seller_data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('itemid')
    )
    op.create_table('MiniItem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itemid', sa.Text(), nullable=True),
    sa.Column('sku', sa.Text(), nullable=True),
    sa.Column('price', sa.Text(), nullable=True),
    sa.Column('originalprice', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('itemid')
    )
    op.create_table('QAItem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itemid', sa.Text(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('question_date', sa.Text(), nullable=True),
    sa.Column('question_author', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('answer_author', sa.Text(), nullable=True),
    sa.Column('answer_date', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('itemid')
    )
    op.create_table('ReviewItem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itemid', sa.Text(), nullable=True),
    sa.Column('review_title', sa.Text(), nullable=True),
    sa.Column('rating', sa.Text(), nullable=True),
    sa.Column('review_date', sa.Text(), nullable=True),
    sa.Column('reviewer', sa.Text(), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('upvode', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('itemid')
    )
    op.drop_table('detailitem_test')
    # ### end Alembic commands ###


def downgrade_data():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detailitem_test',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('desc', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='detailitem_test_pkey')
    )
    op.drop_table('ReviewItem')
    op.drop_table('QAItem')
    op.drop_table('MiniItem')
    op.drop_table('DetailItem')
    # ### end Alembic commands ###

